apiVersion: v1
kind: Service
metadata:
  name: testserver-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: testserver
  ports:
    - protocol: TCP
      port: 5050
      nodePort: 30001
      targetPort: 5050