apiVersion: v1
kind: Service
metadata:
  name: ts-service
  namespace: default
spec:
  selector:
    app: testserver
  type: NodePort
  ports:
    - name: tcp-port
      port: 5050
      targetPort: 5050
      nodePort: 30001
      protocol: TCP
